{
 "title": "jrgnsn-pleroma",
 "tags": [ "pleroma" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Local Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  max(users) AS \"users\"\nFROM stats\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "# Local Posts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  posts\nFROM stats\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Local posts per user",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  posts_users\nFROM stats\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "# Federated Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  federated_users\nFROM stats\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "# Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  servers\nFROM stats\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Unreachable Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  count(days) AS \"days\"\nFROM unreached_servers\nGROUP BY datetime\nORDER BY 1"
    }
   ]
  },
  { "title": "Basic Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Info",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"192.168.228.3:9100\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"user\",instance=\"192.168.228.3:9100\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"iowait\",instance=\"192.168.228.3:9100\"}[5m])) * 100",
     "legendFormat": "Busy IO wait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\".*irq\",instance=\"192.168.228.3:9100\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"192.168.228.3:9100\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode=\"idle\",instance=\"192.168.228.3:9100\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_microseconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_class) (rate(http_requests_total[1m])) * 100",
     "legendFormat": "{{method}} {{status_class}}"
    }
   ]
  },
  { "title": "Federation Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "User Info",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  max(federated_users) AS \"Total Federated Users\"\nFROM stats\nWHERE\n  $__timeFilter(datetime)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  federated_users_hour AS \"Federated User Change\"\nFROM stats\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Unreachable Servers",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  days AS \"days\",\n  server,\n  since\nFROM unreached_servers\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Post Info",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  posts_hour AS \"Local Posts per hour\"\nFROM stats\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  fed_posts_hour AS \"Federated Posts per hour\"\nFROM stats\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  used_disk_space AS \"Total Space Used\"\nFROM stats\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  disc_space_hour AS \"Disk Space (+/-)\"\nFROM stats\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Remote Servers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  servers_hour AS \"Server (+/-)\"\nFROM stats\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  servers AS \"Total Servers\"\nFROM stats\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  { "title": "Phoenix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Channel Join Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "phoenix_channel_join_duration_microseconds_sum"
    }
   ]
  }
 ]
}