CREATE DATABASE pleroma_stats WITH OWNER pleroma;

\c pleroma_stats;

CREATE TABLE stats(
  DATETIME TIMESTAMPTZ PRIMARY KEY NOT NULL,
  USERS INT,
  USERS_HOUR INT,
  POSTS INT,
  POSTS_HOUR INT,
  POSTS_USERS INT,
  INTERACTIONS INT,
  ACTIVE INT,
  ACTIVE30 INT,
  SERVERS INT,
  SERVERS_HOUR INT,
  POSTS_ACTIVE INT,
  FEDERATED_USERS INT,
  FEDERATED_USERS_HOUR INT,
  FED_POSTS_HOUR INT,
  USED_DISK_SPACE INT,
  DISC_SPACE_HOUR INT
);

CREATE TABLE unreached_servers(
  SERVER VARCHAR(30),
  SINCE TIMESTAMP,
  DAYS VARCHAR(30),
  INSERTED_AT TIMESTAMP PRIMARY KEY NOT NULL,
  DATETIME TIMESTAMPTZ
);